### ISSUE TITLE
Add Custom Stock Selection Feature

### ISSUE THREAD

**Issue by Benevalterjr** [adalbertobrant/macd#1]
Current Issue:
    The app only supports predefined stocks for analysis.

Requested Feature:
    Allow users to input and select their own stocks for analysis.

Acceptance Criteria:
    Users can enter custom stock tickers.
    Custom stock selections are saved and used in the analysis.

**Comment by adalbertobrant** [comment]
Thanks for the issue @Benevalterjr , I will try to improve it in another branch here in github

**Comment by adalbertobrant** [comment]
Work is done.
